robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # can control effort (directly) and position (needs PID gains) as a group
  group_effort_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - front_left_joint
      - front_right_joint
      - rear_left_joint
      - rear_right_joint

  # only individual velocity controllers
  front_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  front_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  rear_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_left_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  rear_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_right_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}